### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by tiantian-zhang** [kuppal2/xmsPANDA#4]
Hi Karan, 

I really like the latest version of xmsPANDA and it worked pretty well with the R 4.0 version on my end.  However, I met this error message repeatedly as "Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': undefined columns selected". I think most of figures/tables are done (PCA, HCA, result tables) and xmsPANDA stopped at the ROC.pdf step since the ROC file can't be properly opened.  

Thank you,

Tiantian

**Comment by kuppal2** [comment]
Hi Tiantian,

Thank you for sharing! Please try the updated version: 1.3.1 (release 3/30/2021)

Thank you,
Karan

**Comment by tiantian-zhang** [comment]
Thank you Karan, I updated with the latest version, and now xmsPANDA works well: **Program ended successfully in 2.01 mins. Please see the ReadMe.txt file for description of output files and folders.**
