### ISSUE TITLE
Invalid number of standard colors requested.

### ISSUE THREAD

**Issue by dwalke04** [kuppal2/xmsPANDA#5]
When using the PLS lite function, I have been receiving the following error:

Starting processing... 
Running feature selection method: pls
Performing log2 transformation
[1] "Duplicate features detected"
[1] "Removing duplicate entries for the following features:"
Performing pls analysis
Error in standardColors(length(mycl_metabs)) : 
  Invalid number of standard colors requested.

My code is below.
Thanks!

demetabs_reslite2<-diffexp.lite(Xmat=Xmat,Ymat=Ymat,outloc=outloc,featselmethod="pls",normalization.method = "log2transform",vipthresh=2,foldchangethresh = 0)

**Comment by kuppal2** [comment]
It looks like the number of clusters in your dataset is >400 which is more than the number of standard colors. I have updated the package to address this. Please try re-installing the package to see if the update addresses this error. You might have to include "force=TRUE" if the package is already loaded:

###############
library(devtools);install_github("kuppal2/xmsPANDA",force=TRUE)
###############

**Comment by dwalke04** [comment]
Thank you! This resolved the problem and everything seems to be working well. Great updates and additions to the package, the "lite" functions are fantastic.

Best,
Doug
